# Generated by Django 5.0.1 on 2024-02-02 17:27

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0004_alter_movie_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='duration',
            field=models.FloatField(default=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='language',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='link',
            field=models.URLField(default=datetime.datetime(2024, 2, 2, 17, 27, 56, 893587, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
